"""Generate LaTeX macros, tables and figure includes from formal results.

The generated TeX never hard-codes numerical conclusions in the paper source.
Formal values come from ``05_results``; figure availability comes from the
problem-specific figure manifests in the same result tree.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "05_results"
LATEX = ROOT / "07_paper" / "latex"
GENERATED = LATEX / "generated"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def tex_escape(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text


def fmt(value: float, digits: int = 4) -> str:
    return f"{float(value):.{digits}f}"


def sci_tex(value: float, significant: int = 4) -> str:
    value = float(value)
    if value == 0:
        return "0"
    exponent = int(math.floor(math.log10(abs(value))))
    mantissa = value / (10 ** exponent)
    return rf"{mantissa:.{significant - 1}f}\times 10^{{{exponent}}}"


def write_macros() -> None:
    q1 = load_json(RESULTS / "q1" / "parameters.json")
    q2 = load_json(RESULTS / "q2" / "parameters.json")
    q3 = load_json(RESULTS / "q3" / "parameters.json")
    q4 = load_json(RESULTS / "q4" / "parameters.json")
    reporting = load_json(RESULTS / "reporting_conventions.json")
    delta = reporting["time_offset"]

    macros = {
        "QOneDelta": fmt(delta["q1"]["reported_delta_s"], 4),
        "QTwoDelta": fmt(delta["q2"]["reported_delta_s"], 2),
        "QThreeDelta": fmt(delta["q3"]["reported_delta_s"], 2),
        "QOneRMSE": sci_tex(q1["loss"]["rmse"]),
        "QTwoBiasX": fmt(q2["bias_x_m"], 3),
        "QTwoBiasY": fmt(q2["bias_y_m"], 3),
        "QTwoBiasNorm": fmt(q2["bias_norm_m"], 3),
        "QTwoCorrectedRMSE": fmt(q2["corrected_inter_sensor_rmse_m"], 3),
        "QThreeWaldP": fmt(q3["wald"]["p_value"], 4),
        "QThreeEffectIndex": fmt(q3["wald"]["effect_index"], 4),
        "QThreeBiasNorm": fmt(q3["wald"]["bias_norm"], 3),
        "QFourTaskCount": str(int(q4["selected_task_count"])),
        "QFourShootCount": str(int(q4["shooting_count"])),
        "QFourPhotoCount": str(int(q4["photography_count"])),
        "QFourExpectedHits": fmt(q4["expected_shooting_hits"], 2),
        "QFourMinMargin": fmt(q4["minimum_normalized_margin"], 4),
        "QFourGreedyMargin": fmt(q4["greedy_minimum_margin"], 4),
        "QFourMarginRatio": fmt(
            q4["minimum_normalized_margin"] / q4["greedy_minimum_margin"], 2
        ),
    }
    lines = ["% Auto-generated by scripts/generate_latex_assets.py. Do not edit by hand."]
    for name, value in macros.items():
        lines.append(rf"\newcommand{{\{name}}}{{{value}}}")
    (GENERATED / "result_macros.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_summary_tables() -> None:
    q1 = load_json(RESULTS / "q1" / "parameters.json")
    q2 = load_json(RESULTS / "q2" / "parameters.json")
    q3 = load_json(RESULTS / "q3" / "parameters.json")
    q4 = load_json(RESULTS / "q4" / "parameters.json")
    reporting = load_json(RESULTS / "reporting_conventions.json")["time_offset"]

    offset_table = rf"""% Auto-generated.
\begin{{table}}[htbp]
\centering
\caption{{统一时间偏差口径下的三问估计结果}}
\label{{tab:time-offsets}}
\begin{{tabular}}{{lrrl}}
\toprule
问题 & $\delta$ / s & 输出频率 / Hz & 说明 \\
\midrule
Q1 & {reporting['q1']['reported_delta_s']:.4f} & 10 & 无噪声精确对齐 \\
Q2 & {reporting['q2']['reported_delta_s']:.2f} & 10 & Huber 标定 + KF/RTS \\
Q3 & {reporting['q3']['reported_delta_s']:.2f} & 10 & 偏差检验驱动稳健融合 \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (GENERATED / "table_time_offsets.tex").write_text(offset_table, encoding="utf-8")

    q2_table = rf"""% Auto-generated.
\begin{{table}}[htbp]
\centering
\caption{{问题二时空标定与融合关键结果}}
\label{{tab:q2-calibration}}
\begin{{tabular}}{{lr}}
\toprule
指标 & 数值 \\
\midrule
统一时间偏差 $\delta$ / s & {reporting['q2']['reported_delta_s']:.2f} \\
相对系统偏差 $b_x$ / m & {q2['bias_x_m']:.3f} \\
相对系统偏差 $b_y$ / m & {q2['bias_y_m']:.3f} \\
偏差模 / m & {q2['bias_norm_m']:.3f} \\
校正后两源差值 RMSE / m & {q2['corrected_inter_sensor_rmse_m']:.3f} \\
门控前平均 NIS & {q2['mean_nis']:.3f} \\
白化创新平均 $|\rho_1|$ & {q2['mean_abs_lag1_whitened_innovation']:.4f} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (GENERATED / "table_q2.tex").write_text(q2_table, encoding="utf-8")

    ci_low = q3["bootstrap"]["ci_low"]
    ci_high = q3["bootstrap"]["ci_high"]
    q3_table = rf"""% Auto-generated.
\begin{{table}}[htbp]
\centering
\caption{{问题三系统偏差判定}}
\label{{tab:q3-bias-test}}
\begin{{tabular}}{{lr}}
\toprule
指标 & 数值 \\
\midrule
统一时间偏差 $\delta$ / s & {reporting['q3']['reported_delta_s']:.2f} \\
HAC--Wald $p$ 值 & {q3['wald']['p_value']:.4f} \\
偏差模 / m & {q3['wald']['bias_norm']:.3f} \\
工程效应指数 & {q3['wald']['effect_index']:.4f} \\
Bootstrap 95\% CI ($x$) / m & [{ci_low[0]:.3f}, {ci_high[0]:.3f}] \\
Bootstrap 95\% CI ($y$) / m & [{ci_low[1]:.3f}, {ci_high[1]:.3f}] \\
启用系统偏差状态 & {'是' if q3['bias_state_enabled'] else '否'} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (GENERATED / "table_q3.tex").write_text(q3_table, encoding="utf-8")

    comparison_path = RESULTS / "q4" / "resource_mode_comparison.json"
    comparison = load_json(comparison_path) if comparison_path.is_file() else None
    comparison_line = "尚未生成"
    if comparison:
        exclusive = comparison["exclusive"]
        parallel = comparison["parallel"]
        comparison_line = (
            f"互斥/并行一级最优任务数 = {exclusive['task_count']}/{parallel['task_count']}"
        )
    q4_table = rf"""% Auto-generated.
\begin{{table}}[htbp]
\centering
\caption{{问题四任务调度结果}}
\label{{tab:q4-summary}}
\begin{{tabular}}{{lr}}
\toprule
指标 & 数值 \\
\midrule
模板容量上界 & 9 \\
MILP 最优任务数 & {int(q4['selected_task_count'])} \\
射击任务数 & {int(q4['shooting_count'])} \\
拍照任务数 & {int(q4['photography_count'])} \\
期望命中数 & {q4['expected_shooting_hits']:.2f} \\
MILP 最小归一化裕度 & {q4['minimum_normalized_margin']:.4f} \\
贪心最小归一化裕度 & {q4['greedy_minimum_margin']:.4f} \\
资源假设对照 & {tex_escape(comparison_line)} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    (GENERATED / "table_q4_summary.tex").write_text(q4_table, encoding="utf-8")


def write_schedule_table() -> None:
    path = RESULTS / "q4" / "optimized_schedule.csv"
    frame = pd.read_csv(path)
    columns = ["序号", "目标编号", "任务", "开始准备时刻(s)", "任务执行时刻(s)"]
    missing = [column for column in columns if column not in frame.columns]
    if missing:
        raise ValueError(f"optimized_schedule.csv missing columns: {missing}")
    lines = [
        "% Auto-generated.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{问题四最终九项任务调度}",
        r"\label{tab:q4-schedule}",
        r"\begin{tabular}{cllrr}",
        r"\toprule",
        r"序号 & 目标编号 & 任务 & 开始准备 / s & 执行 / s \\",
        r"\midrule",
    ]
    for _, row in frame[columns].iterrows():
        lines.append(
            f"{int(row['序号'])} & {tex_escape(row['目标编号'])} & {tex_escape(row['任务'])} & "
            f"{float(row['开始准备时刻(s)']):.2f} & {float(row['任务执行时刻(s)']):.2f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    (GENERATED / "table_q4_schedule.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_figure_includes() -> None:
    selections = [
        (1, "objective_scan", "问题一时间偏差目标函数扫描"),
        (1, "aligned_trajectory", "问题一时间对齐后的空间轨迹"),
        (2, "objective_profile", "问题二稳健时空标定目标函数"),
        (2, "fused_trajectory_10hz", "问题二 10 Hz RTS 融合轨迹"),
        (2, "innovation_diagnostics", "问题二创新一致性诊断"),
        (3, "bias_confidence_interval", "问题三系统偏差置信区间"),
        (3, "fused_trajectory_uncertainty", "问题三融合轨迹及模型内不确定性"),
        (4, "trajectory_targets_schedule", "问题四轨迹、目标与最终任务位置"),
        (4, "optimized_schedule_timeline", "问题四最终调度时间线"),
        (4, "constraint_margins", "问题四任务约束裕度"),
    ]
    lines = ["% Auto-generated. Existing formal PDFs are referenced in place."]
    asset_manifest = []
    for problem, stem, caption in selections:
        rel = f"../../06_figures/q{problem}/{stem}.pdf"
        label = f"fig:auto-q{problem}-{stem.replace('_', '-')}"
        lines += [
            rf"\IfFileExists{{{rel}}}{{%",
            r"\begin{figure}[htbp]",
            r"  \centering",
            rf"  \includegraphics[width=0.88\textwidth,height=0.68\textheight,keepaspectratio]{{{rel}}}",
            rf"  \caption{{{caption}}}",
            rf"  \label{{{label}}}",
            r"\end{figure}",
            r"}{% figure omitted when the formal PDF is absent }",
            "",
        ]
        asset_manifest.append({"problem": problem, "stem": stem, "path": rel, "caption": caption})
    (GENERATED / "figures.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (GENERATED / "latex_asset_manifest.json").write_text(
        json.dumps(asset_manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def main() -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    write_macros()
    write_summary_tables()
    write_schedule_table()
    write_figure_includes()
    print(f"[generate_latex_assets] PASS -> {GENERATED}")


if __name__ == "__main__":
    main()
